// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	imdb "github.com/clambin/imdb-watchlist/pkg/imdb"
	mock "github.com/stretchr/testify/mock"
)

// Reader is an autogenerated mock type for the Reader type
type Reader struct {
	mock.Mock
}

type Reader_Expecter struct {
	mock *mock.Mock
}

func (_m *Reader) EXPECT() *Reader_Expecter {
	return &Reader_Expecter{mock: &_m.Mock}
}

// GetWatchlist provides a mock function with given fields: listID
func (_m *Reader) GetWatchlist(listID string) (imdb.Watchlist, error) {
	ret := _m.Called(listID)

	if len(ret) == 0 {
		panic("no return value specified for GetWatchlist")
	}

	var r0 imdb.Watchlist
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (imdb.Watchlist, error)); ok {
		return rf(listID)
	}
	if rf, ok := ret.Get(0).(func(string) imdb.Watchlist); ok {
		r0 = rf(listID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(imdb.Watchlist)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(listID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Reader_GetWatchlist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWatchlist'
type Reader_GetWatchlist_Call struct {
	*mock.Call
}

// GetWatchlist is a helper method to define mock.On call
//   - listID string
func (_e *Reader_Expecter) GetWatchlist(listID interface{}) *Reader_GetWatchlist_Call {
	return &Reader_GetWatchlist_Call{Call: _e.mock.On("GetWatchlist", listID)}
}

func (_c *Reader_GetWatchlist_Call) Run(run func(listID string)) *Reader_GetWatchlist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Reader_GetWatchlist_Call) Return(entries imdb.Watchlist, err error) *Reader_GetWatchlist_Call {
	_c.Call.Return(entries, err)
	return _c
}

func (_c *Reader_GetWatchlist_Call) RunAndReturn(run func(string) (imdb.Watchlist, error)) *Reader_GetWatchlist_Call {
	_c.Call.Return(run)
	return _c
}

// NewReader creates a new instance of Reader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *Reader {
	mock := &Reader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
