apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service.yaml
- deployment.yaml
secretGenerator:
- literals:
  - api_key=$SONARR_APIKEY
  - list_id=$IMDB_LISTID
  name: watchlist
  type: Opaque
images:
- name: ghcr.io/clambin/imdb-watchlist
  newTag: $TAG      
