apiVersion: apps/v1
kind: Deployment
metadata:
  name: watchlist
  labels:
    app: watchlist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watchlist
  template:
    metadata:
      labels:
        app: watchlist
    spec:
      containers:
      - name: watchlist
        image: ghcr.io/clambin/imdb-watchlist
        envFrom:
        - secretRef:
            name: watchlist
        args:
        - '--apikey=$(api_key)'
        - '--list=$(list_id)'
        resources:
          requests:
            cpu: 2m
            memory: 20Mi
          limits:
            memory: 40Mi
