name: staged build

on:
  push:
    branches:
      - docker

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v5.5.1
        id: docker_meta
        with:
          images: ghcr.io/clambin/imdb-watchlist
          tags: |
            type=sha
            type=semver,pattern={{version}}
      - name: get branch
        shell: bash
        run: |
          echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: build/Dockerfile-staged
          platforms: linux/amd64,linux/arm,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          build-args: |
            VERSION=${{ env.BRANCH }}-${{ steps.docker_meta.outputs.version }}
