name: staged build

on:
  push:
    branches:
      - docker

jobs:
  build:
    uses: ./.github/workflows/docker-build.yaml
    with:
      image: ghcr.io/clambin/imdb-watchlist
      dockerfile: build/Dockerfile-staged
